[openai]
base_url = "https://api.openai.com/v1"
env_key_name = "OPENAI_API_KEY"

[ollama]
base_url = "http://192.168.0.101:11434/v1"

[together]
base_url = "https://api.together.xyz/v1"
env_key_name = "TOGETHER_API_KEY"

[groq]
base_url = "https://api.groq.com/openai/v1"
env_key_name = "GROQ_API_KEY"

[anthropic]
base_url = "https://api.anthropic.com/v1"
env_key_name = "ANTHROPIC_API_KEY"

[openrouter]
base_url = "https://openrouter.ai/api/v1"
env_key_name = "OPENROUTER_API_KEY"

[deepseek]
base_url = "https://api.deepseek.com/v1"
env_key_name = "DEEPSEEK_API_KEY"
